sudo: required

env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/usr/bin/:$PATH

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6

# command to install dependencies

before_install:
  - wget https://github.com/jgm/pandoc/releases/download/1.19.1/pandoc-1.19.1-1-amd64.deb && ar p pandoc-1.19.1-1-amd64.deb data.tar.gz | tar zx
  - sudo pip install --upgrade pip
  - sudo apt-get install chktex

install:
    - sudo pip install .

script:
  - make -C test
  - chktex -W # Print version information.
  - chktex -q -n 6 test/*.tex 2>/dev/null | tee lint.out
  - test ! -s lint.out